### ISSUE TITLE
Tocar música de fundo genérica

### ISSUE THREAD

**Issue by gabrielluizep** [Nidhoogr/Yggdrasil#10]

**Comment by leonardodod** [comment]
# Feito!
## Segue imagens do código responsável por este efeito em jogo.
![image](https://user-images.githubusercontent.com/74744977/113462112-c1a4b680-93f5-11eb-8abd-d2a76138f6f1.png)
Carregando o áudio para a cena.
![image](https://user-images.githubusercontent.com/74744977/113462125-cec1a580-93f5-11eb-8130-f71134383b59.png)
Adicionando o áudio na cena.
![image](https://user-images.githubusercontent.com/74744977/113462164-f7e23600-93f5-11eb-8b71-9999bb0b4239.png)
Verificação de evento, música de fundo para de tocar quando o jogador "cai".
## Fonte de onde foi retirado a música:
https://www.looperman.com/loops/detail/244133/hyperpop-type-loop-pixel-time-free-145bpm-8bit-chiptune-synth-loop
