### ISSUE TITLE
Definir 2 ou mais cenas

### ISSUE THREAD

**Issue by gabrielluizep** [Nidhoogr/Yggdrasil#11]

**Comment by leonardodod** [comment]
Não se aplica.
O jogo é gerado infinitamente na mesma cena.

**Comment by boidacarapreta** [comment]
> Não se aplica.
> O jogo é gerado infinitamente na mesma cena.

Mas há várias cenas: de [abertura](https://github.com/Nidhoogr/Yggdrasil/blob/dev/src/index.js#L8) até [encerramento](https://github.com/Nidhoogr/Yggdrasil/blob/dev/src/index.js#L11). A tarefa foi, sim, atendida.
