### ISSUE TITLE
Definir e projetar tela de abertura

### ISSUE THREAD

**Issue by gabrielluizep** [Nidhoogr/Yggdrasil#12]

**Comment by leonardodod** [comment]
# Feito!
## Segue:
![image](https://user-images.githubusercontent.com/74744977/112402552-81ee1880-8ceb-11eb-85fb-d944f9137563.png)
![image](https://user-images.githubusercontent.com/74744977/112402585-8e727100-8ceb-11eb-8155-32ceaea1861d.png)
Serão adicionados mais detalhes em futuros commits.
