### ISSUE TITLE
Tocar sons genéricos de efeito gerados por eventos do jogo

### ISSUE THREAD

**Issue by gabrielluizep** [Nidhoogr/Yggdrasil#15]

**Comment by leonardodod** [comment]
# Feito!
## Segue imagens do código responsável por esta ação no jogo.
![image](https://user-images.githubusercontent.com/74744977/113462550-d97d3a00-93f7-11eb-88c6-859803edc562.png)
As últimas três linhas estão carregando os áudios para a cena.
![image](https://user-images.githubusercontent.com/74744977/113462599-0cbfc900-93f8-11eb-9f80-0d0b13a84fd8.png)
Nesta parte estamos definindo a amplitude de cada um dos áudios adicionados e adicionando eles na cena.
![image](https://user-images.githubusercontent.com/74744977/113462660-59a39f80-93f8-11eb-88cd-03e07a0d1d3c.png)
Aqui temos o evento acionado pelo jogador que gera o som de pulo aleatoriamente entre os três carregados anteriormente.
## Fonte de onde foi retirado os áudios:
(link vai ser posto futuramente)
