### ISSUE TITLE
Animar sprites genéricos

### ISSUE THREAD

**Issue by gabrielluizep** [Nidhoogr/Yggdrasil#18]

**Comment by leonardodod** [comment]
# Feito!
## Segue imagem do código responsável pelo efeito parallax:
![image](https://user-images.githubusercontent.com/74744977/113463506-6cb86e80-93fc-11eb-9c83-e95cff8cd7b5.png)
![image](https://user-images.githubusercontent.com/74744977/113463514-74781300-93fc-11eb-95b9-970190ade434.png)
![image](https://user-images.githubusercontent.com/74744977/113463526-86f24c80-93fc-11eb-99a5-11bdc9e654a2.png)
Estes códigos fazem com que as sprites definidas como as camadas 1, 3 e 4 e fossem adicionadas à cena de forma que ao saírem da cena sejam recriadas do outro lado.
![image](https://user-images.githubusercontent.com/74744977/113463605-2dd6e880-93fd-11eb-97fc-c35c382365a7.png)
E aqui podemos definir a velocidade com que cada sprite irá se deslocar no eixo X.
## Segue imagem do código responsável pela animação personagem do jogador:
![image](https://user-images.githubusercontent.com/74744977/113463685-ae95e480-93fd-11eb-8c6a-00634f7ff2ee.png)
Sprite de animação de corrida adicionado em #19 sendo aplicado.
![image](https://user-images.githubusercontent.com/74744977/113463707-d71dde80-93fd-11eb-8fe4-566b5ecb8766.png)
Sprite de animação de pulo adicionado em #19 sendo aplicado.
![image](https://user-images.githubusercontent.com/74744977/113463726-f4eb4380-93fd-11eb-8a17-c6238347daaa.png)
Código para garantir que quando o jogador estiver encostando na plataforma, a animação de corrida esteja em andamento, e quando não, a animação de pulo a substitua.
