### ISSUE TITLE
Usar sprites genéricos de animação

### ISSUE THREAD

**Issue by gabrielluizep** [Nidhoogr/Yggdrasil#19]

**Comment by leonardodod** [comment]
# Feito!
## Segue imagem do código responsável por adicionar as sprites de animação do personagem do jogador:
![image](https://user-images.githubusercontent.com/74744977/113463875-fff2a380-93fe-11eb-9a02-bc4b67d9299b.png)
Este código carrega as sprites na cena.
![image](https://user-images.githubusercontent.com/74744977/113463885-23b5e980-93ff-11eb-8def-2ec8e2f07f37.png)
Estes códigos adicionam cada uma das sprites das camadas, inclusive das plataformas. Mas isto já fora comentado em #20
