### ISSUE TITLE
Usar imagem genérica de fundo

### ISSUE THREAD

**Issue by gabrielluizep** [Nidhoogr/Yggdrasil#20]

**Comment by leonardodod** [comment]
# Feito!
## Segue imagens de fundo utilizadas no jogo.
![layer0](https://user-images.githubusercontent.com/74744977/113462867-68d71d00-93f9-11eb-8a92-e2f9b6bc371b.png)
Camada 0.
![layer1](https://user-images.githubusercontent.com/74744977/113462880-7391b200-93f9-11eb-8606-9116179753cd.png)
Camada 1.
![layer2](https://user-images.githubusercontent.com/74744977/113462885-78eefc80-93f9-11eb-8be5-35e84fdc95aa.png)
Camada 2.
![layer3](https://user-images.githubusercontent.com/74744977/113462886-79879300-93f9-11eb-9eb1-a53b7ebec1d5.png)
Camada 3.
![layer4](https://user-images.githubusercontent.com/74744977/113462887-7a202980-93f9-11eb-8767-c914affb435a.png)
Camada 4.
![image](https://user-images.githubusercontent.com/74744977/113462987-eef36380-93f9-11eb-9936-c87a86eb0f2e.png)
Efeito final.
## Fonte de onde foi retirado as sprites:
https://edermunizz.itch.io/free-pixel-art-plataformer-painted-style
## Segue imagem do código usado para adicionar estas sprites no jogo.
![image](https://user-images.githubusercontent.com/74744977/113463082-590c0880-93fa-11eb-85a0-3008795617f4.png)
Importando as imagens para serem usadas posteriormente.
![image](https://user-images.githubusercontent.com/74744977/113463251-31697000-93fb-11eb-948b-977541ac4f82.png)
Carregando as imagens para a cena.
![image](https://user-images.githubusercontent.com/74744977/113463383-c66c6900-93fb-11eb-8b7c-574ea048fa88.png)
Código usado para adicionar as imagens de forma estática, porém atualmente só é utilizado nestas duas camadas, o resto é feito de outra forma, que será abordado mais detalhadamente na #18
