### ISSUE TITLE
Publicar a versão v0.1 do jogo no GitHub Pages

### ISSUE THREAD

**Issue by gabrielluizep** [Nidhoogr/Yggdrasil#21]

**Comment by leonardodod** [comment]
# Feito!
## Jogo já está publicado.
https://nidhoogr.boidacarapreta.cc

**Comment by boidacarapreta** [comment]
> # Feito!
> ## Jogo já está publicado.
> https://nidhoogr.boidacarapreta.cc

Esta URL se refere a #30. Como está além desta tarefa, também a atende.
