### ISSUE TITLE
Criar placar local em memória não persistente

### ISSUE THREAD

**Issue by gabrielluizep** [Nidhoogr/Yggdrasil#22]

**Comment by leonardodod** [comment]
# Feito!
## Segue imagem do efeito em jogo.
![image](https://user-images.githubusercontent.com/74744977/113479115-71fcd400-9463-11eb-8736-cc47840cf1b3.png)
Criado o contador de pontos no canto superior esquerdo que incrementa o valor conforme o passar do tempo.
![image](https://user-images.githubusercontent.com/74744977/113479164-c99b3f80-9463-11eb-9a55-65d922244509.png)
Exemplo de valor incrementado.
![image](https://user-images.githubusercontent.com/74744977/113479274-7970ad00-9464-11eb-9bad-3f0eeb89b532.png)
Adicionando o texto no canto superior esquerdo.
![image](https://user-images.githubusercontent.com/74744977/113479281-82fa1500-9464-11eb-8d03-5bef17782fc7.png)
Incrementando o valor com o passar do tempo.
