### ISSUE TITLE
Definir o jogo

### ISSUE THREAD

**Issue by gabrielluizep** [Nidhoogr/Yggdrasil#3]
Deve-se ser definido:

* Referências: literatura, mídias em geral e outros jogos;
* Roteiro: início, meio e fim;
* Personagens: perfis, evolução;
* Artefatos: armas, poções etc;
* Mundo/universo.

**Comment by leonardodod** [comment]
#Referências:

##Níðhöggr | Nidhogg

![image](https://user-images.githubusercontent.com/74744977/111853678-cdbf4d00-88fa-11eb-9afb-98f8c2e15106.png)

O dragão da mitologia nórdica, que consome os injustos e rói as raízes de Yggdrasil.

## Yggdrasil

![image](https://user-images.githubusercontent.com/74744977/111853740-09f2ad80-88fb-11eb-98d9-05f2928aa416.png)

Temos  como referência o estilo de jogo infinity runner.

Todos os outros pontos serão situados na cultura nórdica para condizer com a proposta, mundo | universo, personagens e artefatos.

## Roteiro

O momento tão aguardado por Nidhogg finalmente chegou, **O RAGNAROK** está aqui, tudo que você conhecia está ruindo perante seus olhos, sua família e amigos não existem mais. Você deve correr por sua vida, pois Nidhogg julgou-lhe desonesto, mas ele também está farto de roer raízes.
